language: java
jobs:
  include:
    - arch: amd64
    - arch: ppc64le
      before_install: 
        - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xf -C /opt
        - export MAVEN_HOME=/opt/apache-maven-3.6.3
        - export PATH=${MAVEN_HOME}/bin:${PATH}
after_failure: print_surefire_reports.sh
